// Generated by FlutterFire CLI — run `flutterfire configure` to replace this.
// See TASKS.md Phase 4 for full setup instructions.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw _notConfigured;
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => throw _notConfigured,
      TargetPlatform.iOS     => throw _notConfigured,
      _ => throw _notConfigured,
    };
  }

  static final _notConfigured = UnimplementedError(
    'Firebase is not configured.\n'
    'Run: dart pub global activate flutterfire_cli\n'
    'Then: flutterfire configure\n'
    'This will overwrite this file with your real Firebase options.',
  );
}
